#!/usr/bin/env python3
"""
List all Databricks Knowledge Assistant (KA) Agent Bricks endpoints.

Writes results to data/ka.list. Uses the Knowledge Assistants REST API
(GET /api/2.1/knowledge-assistants). Requires DATABRICKS_HOST and DATABRICKS_TOKEN in .env.local.

Colored terminal output follows doc/agent-script-style.md (NO_COLOR, --no-color).

Usage:
  uv run python scripts/list_ka_endpoints.py
  uv run python scripts/list_ka_endpoints.py --output data/ka.list
  uv run python scripts/list_ka_endpoints.py --format json
"""

import argparse
import json
import os
import sys
from pathlib import Path

# Load .env.local before other imports
ROOT = Path(__file__).resolve().parents[1]
if (ROOT / ".env.local").exists():
    from dotenv import load_dotenv
    load_dotenv(ROOT / ".env.local", override=True)


def _use_color() -> bool:
    if os.environ.get("NO_COLOR", "").strip():
        return False
    return sys.stdout.isatty()


def _theme(use_color: bool):
    if not use_color:

        class _NS:
            R = G = Y = B = M = C = W = BOLD = DIM = ""
            OK = "[OK]"
            FAIL = "[FAIL]"
            WARN = "[WARN]"

        return _NS()

    class _NS:
        R = "\033[31m"
        G = "\033[32m"
        Y = "\033[33m"
        B = "\033[34m"
        M = "\033[35m"
        C = "\033[36m"
        W = "\033[0m"
        BOLD = "\033[1m"
        DIM = "\033[2m"
        OK = f"{G}✓{W}"
        FAIL = f"{R}✗{W}"
        WARN = f"{Y}⚠{W}"

    return _NS()


# Monospace-aligned table: space-padded columns, " | " separators (see build_ka_list_text).
KA_LIST_COL_SEP = " | "
# Header/ruler use "# " so comments work; data rows use the same width prefix so | lines up.
KA_LIST_DATA_PREFIX = "  "


def _ka_row_cells(ka: dict) -> list[str] | None:
    """Return one data row, or None if no serving endpoint yet."""
    endpoint = ka.get("endpoint_name", "")
    if not endpoint:
        return None
    return [
        endpoint,
        ka.get("display_name", ""),
        ka.get("id", ""),
        ka.get("name", ""),
        ka.get("state", ""),
    ]


def _column_widths(header: list[str], data_rows: list[list[str]]) -> list[int]:
    all_rows: list[list[str]] = [header] + data_rows
    n = len(header)
    return [max(len(all_rows[r][i]) for r in range(len(all_rows))) for i in range(n)]


def _fmt_aligned_row(cells: list[str], widths: list[int]) -> str:
    return KA_LIST_COL_SEP.join(str(c).ljust(widths[i]) for i, c in enumerate(cells))


def build_ka_list_text(kas: list[dict]) -> str:
    """Write ka.list body: fixed-width columns so | lines up in a monospace editor."""
    header = ["serving_endpoint", "display_name", "ka_id", "full_name", "state"]
    rows: list[list[str]] = []
    for ka in kas:
        r = _ka_row_cells(ka)
        if r is not None:
            rows.append(r)
    if not rows:
        widths = [len(h) for h in header]
    else:
        widths = _column_widths(header, rows)
    ruler = ["-" * widths[i] for i in range(len(header))]
    out = [
        "# Databricks Knowledge Assistant (KA) Agent Bricks endpoints",
        "# Generated by scripts/list_ka_endpoints.py",
        "",
        "# " + _fmt_aligned_row(ruler, widths),
        "# " + _fmt_aligned_row(header, widths),
        "# " + _fmt_aligned_row(ruler, widths),
    ]
    out.extend(KA_LIST_DATA_PREFIX + _fmt_aligned_row(r, widths) for r in rows)
    return "\n".join(out) + "\n"


def print_ka_terminal_line(ka: dict, t) -> None:
    """Colored inline row: endpoint TAB display_name as: 'name : <display_name>'."""
    endpoint = ka.get("endpoint_name", "")
    display_name = ka.get("display_name", "")
    if not endpoint:
        eid = ka.get("id", "")
        print(
            f"  {t.WARN}  {t.DIM}id : {eid}{t.W} (no endpoint yet)",
            file=sys.stdout,
        )
        return
    if t.G:
        print(
            f"{t.BOLD}{t.B}{endpoint}{t.W}\t"
            f"{t.DIM}display_name as:{t.W} "
            f"{t.G}'name : {display_name}'{t.W}"
        )
    else:
        print(f"{endpoint}\tdisplay_name as: 'name : {display_name}'")


def list_knowledge_assistants() -> list[dict]:
    """Fetch all Knowledge Assistants via REST API (GET /api/2.1/knowledge-assistants)."""
    import urllib.request
    import urllib.error

    host = os.environ.get("DATABRICKS_HOST", "").strip().rstrip("/")
    token = os.environ.get("DATABRICKS_TOKEN", "").strip()
    if not host or not token:
        raise ValueError(
            "DATABRICKS_HOST and DATABRICKS_TOKEN must be set in .env.local. "
            "Run: databricks auth login, then add both to .env.local."
        )

    url = f"{host}/api/2.1/knowledge-assistants"
    headers = {"Authorization": f"Bearer {token}"}
    items = []
    page_token = None

    while True:
        params = {"page_size": 100}
        if page_token:
            params["page_token"] = page_token
        qs = "&".join(f"{k}={v}" for k, v in params.items())
        full_url = f"{url}?{qs}" if qs else url
        req = urllib.request.Request(full_url, headers=headers, method="GET")
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = json.loads(resp.read().decode())
        except urllib.error.HTTPError as e:
            body = e.read().decode() if e.fp else ""
            if e.code == 404:
                print("Knowledge Assistants API not available (404). Ensure workspace supports Agent Bricks.", file=sys.stderr)
                return []
            if e.code == 403:
                print("Access denied (403). Ensure your token has knowledge-assistants scope.", file=sys.stderr)
                return []
            raise RuntimeError(f"API error {e.code}: {body}") from e
        batch = data.get("knowledge_assistants") or []
        items.extend(batch)
        page_token = data.get("next_page_token")
        if not page_token:
            break
    return items




def main():
    parser = argparse.ArgumentParser(description="List Databricks Knowledge Assistant endpoints")
    parser.add_argument(
        "--output",
        "-o",
        default=str(ROOT / "data" / "ka.list"),
        help="Output file (default: data/ka.list)",
    )
    parser.add_argument(
        "--format",
        choices=["list", "json"],
        default="list",
        help="Output format: list (one per line) or json",
    )
    parser.add_argument(
        "--no-color",
        "--plain",
        action="store_true",
        help="Plain text (no ANSI colors); also respects NO_COLOR env",
    )
    args = parser.parse_args()

    use_color = _use_color() and not args.no_color
    t = _theme(use_color)

    try:
        kas = list_knowledge_assistants()
    except Exception as e:
        print(f"Error listing Knowledge Assistants: {e}", file=sys.stderr)
        sys.exit(1)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if args.format == "json":
        out_path.write_text(json.dumps(kas, indent=2))
        print(f"Wrote {len(kas)} Knowledge Assistants to {out_path}", file=sys.stderr)
        return

    out_path.write_text(build_ka_list_text(kas))

    print(file=sys.stdout)
    print(f"{t.BOLD}{t.C}═══ List Knowledge Assistant endpoints ═══{t.W}", file=sys.stdout)
    print(f"{t.DIM}  output: {out_path}{t.W}", file=sys.stdout)
    print(file=sys.stdout)
    print(f"{t.BOLD}{t.B}── Endpoints ──{t.W}", file=sys.stdout)
    for ka in kas:
        print_ka_terminal_line(ka, t)
    print(file=sys.stdout)
    print(f"{t.BOLD}{t.C}── Summary ──{t.W}", file=sys.stdout)
    print(
        f"  {t.OK}  wrote {t.G}{len(kas)}{t.W} Knowledge Assistants to {out_path}",
        file=sys.stdout,
    )
    print(file=sys.stdout)


if __name__ == "__main__":
    main()
