#!/usr/bin/env python3
"""
List all Databricks Knowledge Assistant (KA) Agent Bricks endpoints.

Writes results to data/ka.list. Uses the Knowledge Assistants REST API
(GET /api/2.1/knowledge-assistants). Requires DATABRICKS_HOST and DATABRICKS_TOKEN in .env.local.

Usage:
  uv run python scripts/list_ka_endpoints.py
  uv run python scripts/list_ka_endpoints.py --output data/ka.list
  uv run python scripts/list_ka_endpoints.py --format json
"""

import argparse
import json
import os
import sys
from pathlib import Path

# Load .env.local before other imports
ROOT = Path(__file__).resolve().parents[1]
if (ROOT / ".env.local").exists():
    from dotenv import load_dotenv
    load_dotenv(ROOT / ".env.local", override=True)


def list_knowledge_assistants() -> list[dict]:
    """Fetch all Knowledge Assistants via REST API (GET /api/2.1/knowledge-assistants)."""
    import urllib.request
    import urllib.error

    host = os.environ.get("DATABRICKS_HOST", "").strip().rstrip("/")
    token = os.environ.get("DATABRICKS_TOKEN", "").strip()
    if not host or not token:
        raise ValueError(
            "DATABRICKS_HOST and DATABRICKS_TOKEN must be set in .env.local. "
            "Run: databricks auth login, then add both to .env.local."
        )

    url = f"{host}/api/2.1/knowledge-assistants"
    headers = {"Authorization": f"Bearer {token}"}
    items = []
    page_token = None

    while True:
        params = {"page_size": 100}
        if page_token:
            params["page_token"] = page_token
        qs = "&".join(f"{k}={v}" for k, v in params.items())
        full_url = f"{url}?{qs}" if qs else url
        req = urllib.request.Request(full_url, headers=headers, method="GET")
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = json.loads(resp.read().decode())
        except urllib.error.HTTPError as e:
            body = e.read().decode() if e.fp else ""
            if e.code == 404:
                print("Knowledge Assistants API not available (404). Ensure workspace supports Agent Bricks.", file=sys.stderr)
                return []
            if e.code == 403:
                print("Access denied (403). Ensure your token has knowledge-assistants scope.", file=sys.stderr)
                return []
            raise RuntimeError(f"API error {e.code}: {body}") from e
        batch = data.get("knowledge_assistants") or []
        items.extend(batch)
        page_token = data.get("next_page_token")
        if not page_token:
            break
    return items




def main():
    parser = argparse.ArgumentParser(description="List Databricks Knowledge Assistant endpoints")
    parser.add_argument(
        "--output", "-o",
        default=str(ROOT / "data" / "ka.list"),
        help="Output file (default: data/ka.list)",
    )
    parser.add_argument(
        "--format",
        choices=["list", "json"],
        default="list",
        help="Output format: list (one per line) or json",
    )
    args = parser.parse_args()

    try:
        kas = list_knowledge_assistants()
    except Exception as e:
        print(f"Error listing Knowledge Assistants: {e}", file=sys.stderr)
        sys.exit(1)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if args.format == "json":
        out_path.write_text(json.dumps(kas, indent=2))
        print(f"Wrote {len(kas)} Knowledge Assistants to {out_path}", file=sys.stderr)
        return

    # list format: one endpoint per line, with id and name for reference
    lines = []
    lines.append("# Databricks Knowledge Assistant (KA) Agent Bricks endpoints")
    lines.append(f"# Generated by scripts/list_ka_endpoints.py")
    lines.append("")
    for ka in kas:
        eid = ka.get("id", "")
        name = ka.get("name", "")
        display_name = ka.get("display_name", "")
        endpoint = ka.get("endpoint_name", "")
        state = ka.get("state", "")
        if endpoint:
            lines.append(f"{endpoint}\t# id={eid} name={name} display_name={display_name} state={state}")
        else:
            lines.append(f"# id={eid} name={name} (no endpoint yet, state={state})")
    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(kas)} Knowledge Assistants to {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
